---
- name: Copy join to nodes
  copy: 
    dest: /opt/kubejoin.sh
    src: ./join/kubejoin.sh
    mode: '0700'

- name: Add shebang to kubejoin script
  lineinfile:
    path: /opt/kubejoin.sh
    line: "#!/bin/bash"
    insertbefore: BOF
    
- name: Run kubejoin
  command: /opt/kubejoin.sh
