---
- name: Copy join to nodes
  copy: 
    dest: /opt/kubejoin.sh
    src: ./join/kubejoin.sh
    mode: '0700'

- name: Add shebang to kubejoin script
  lineinfile:
    path: /opt/kubejoin.sh
    line: "#!/bin/bash"
    insertbefore: BOF
    
- name: Check if port 10250 is in use
  shell: "netstat -tuln | grep ':10250 '"
  register: port_check
  ignore_errors: true

- name: Run kubejoin script if port is not in use
  command: /opt/kubejoin.sh
  when: port_check.rc != 0 
