---
- name: Install docker prereqs
  apt: 
    update_cache: yes
    name: "{{ item }}"
  loop: "{{ docker_prereqs_pks }}"

- name: add GCP key
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository
  apt_repository: 
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

- name: install docker
  apt:
    name: "{{ item }}"
  loop: "{{ docker_packages }}"