- name: Install k8s and Docker pkgs
  become: yes
  hosts: gcp_k8s_all
  roles:
    - update_instances
    - docker
    - k8s-all
- name: Setup master node
  become: yes
  hosts: gcp_master_k8s_master
  roles:
    - k8s-master
- name: Setup Worker node
  become: yes
  hosts: gcp_worker_k8s_worker
  roles:
    - k8s-worker
